### ISSUE TITLE
Any alternative of Infura IPFS?

### ISSUE THREAD

**Issue by jsn-hnt** [Karan9034/gfg-enigma#5]
[Infura is currently limiting IPFS services to customers that already have an active IPFS key. New IPFS key creation is disabled for new and existing customers.](https://docs.infura.io/api/networks/ipfs)

**Comment by Karan9034** [comment]
Aware of this issue. You'll have to change the whole IPFS integration with NFT.Storage. Pinata Cloud or Arwave. Many changes on the frontend will be required.
